name: ARM Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for ARM
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build the project
        run: |
          docker run --rm --platform linux/arm64 -v ${{ github.workspace }}:/workspace -w /workspace debian:latest bash build-arm.sh